version: "3.8"
services:
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    restart: always
    volumes:
      -  ./html:/var/www/html
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db-server:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 12345678
      WORDPRESS_DB_NAME: wordpress_db
    depends_on:
      - db-server
    links:
      - db-server

  db-server:
    container_name: database
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root12345678
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345678
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
      image: phpmyadmin
      restart: always
      ports:
        - "8081:80"
      environment:
        PMA_HOST: db-server
        PMA_USER: admin
        PMA_PASSWORD: 12345678
      links:
        - db-server

volumes:
  mysql: {}
